/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;


import controller.Controller;
import java.util.List;
import javax.swing.JOptionPane;
import util.Otpremnica;
import util.TableModelOtpremnica;
import util.TableModelVozac;
import util.User;
import util.Vozac;

/**
 *
 * @author Marko
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     * @param user
     */
    public MainForm(User user) {
        initComponents();
        JOptionPane.showMessageDialog(this, "Dobrodosli: " + user.getMail());
        jLabel5.setText("Ulogovani korisnik: " + user.getMail());
        jTable1.setShowGrid (false);
        jTable2.setShowGrid (false);
        fillTableVozac();
        fillTableOtpremnica();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCreateV = new javax.swing.JButton();
        btnUpdateV = new javax.swing.JButton();
        btnDeleteV = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnDetails = new javax.swing.JButton();
        btnUpdateO = new javax.swing.JButton();
        btnDetailsV = new javax.swing.JButton();
        btnCreateO = new javax.swing.JButton();
        btnDeleteO = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Vozač");

        btnCreateV.setText("Kreiraj");
        btnCreateV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateVActionPerformed(evt);
            }
        });

        btnUpdateV.setText("Azuriraj");
        btnUpdateV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateVActionPerformed(evt);
            }
        });

        btnDeleteV.setText("Obriši");
        btnDeleteV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteVActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Otpremnica");

        btnDetails.setText("Detalji");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });

        btnUpdateO.setText("Azuriraj");
        btnUpdateO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateOActionPerformed(evt);
            }
        });

        btnDetailsV.setText("Detalji");
        btnDetailsV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsVActionPerformed(evt);
            }
        });

        btnCreateO.setText("Kreiraj");
        btnCreateO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateOActionPerformed(evt);
            }
        });

        btnDeleteO.setText("Obriši");
        btnDeleteO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteOActionPerformed(evt);
            }
        });

        jLabel3.setText("treba dodati u azuriraj za vozaca vrstu vozaca da izabere");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(67, 67, 67)
                        .addComponent(btnDetailsV)
                        .addGap(18, 18, 18)
                        .addComponent(btnCreateV)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateV)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteV))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32)
                        .addComponent(btnDetails)
                        .addGap(18, 18, 18)
                        .addComponent(btnCreateO)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateO)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteO))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(64, 64, 64)
                .addComponent(jLabel3)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnCreateV)
                    .addComponent(btnUpdateV)
                    .addComponent(btnDeleteV)
                    .addComponent(btnDetailsV))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel3)))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnDetails)
                    .addComponent(btnCreateO)
                    .addComponent(btnUpdateO)
                    .addComponent(btnDeleteO))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteVActionPerformed
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "morate da izaberete neko polje", "greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        List<Vozac> listVozac = Controller.getInstance().getListVozac();
        Vozac deleteVozac = listVozac.get(selectedRow);
        boolean result = Controller.getInstance().deleteVozac(deleteVozac);

        if (result) {
            JOptionPane.showMessageDialog(this, "uspesno izbrisan vozac");

        } else {
            JOptionPane.showMessageDialog(this, "greska pri brisanju iz baze", "greska", JOptionPane.ERROR_MESSAGE);
        }
        fillTableVozac();

    }//GEN-LAST:event_btnDeleteVActionPerformed

    private void btnCreateVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateVActionPerformed
        Controller.getInstance().createVozac();
        fillTableVozac();
    }//GEN-LAST:event_btnCreateVActionPerformed

    private void btnUpdateVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateVActionPerformed
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "morate da izaberete neko polje", "greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        List<Vozac> listVozac = Controller.getInstance().getListVozac();
        Vozac updateVozac = listVozac.get(selectedRow);

        UpdateVozacForm u = new UpdateVozacForm(this, true, updateVozac);
        u.setLocationRelativeTo(null);
        u.setVisible(true);

        fillTableVozac();
    }//GEN-LAST:event_btnUpdateVActionPerformed

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        int selectedRow = jTable2.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "morate da izaberete neko polje", "greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        List<Otpremnica> listOtpremnica = Controller.getInstance().getListOtpremnica();
        Otpremnica otpremnica = listOtpremnica.get(selectedRow);

        DetailsOtpremnicaForm otpremnicaForm = new DetailsOtpremnicaForm(this, true, otpremnica);
        otpremnicaForm.setLocationRelativeTo(null);
        otpremnicaForm.setVisible(true);
    }//GEN-LAST:event_btnDetailsActionPerformed

    private void btnUpdateOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateOActionPerformed
        int selectedRow = jTable2.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "morate da izaberete neko polje", "greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        List<Otpremnica> listOtpremnica = Controller.getInstance().getListOtpremnica();
        Otpremnica otpremnica = listOtpremnica.get(selectedRow);

        UpdateOtpremnicaForm otpremnicaForm = new UpdateOtpremnicaForm(this, true, otpremnica);
        otpremnicaForm.setLocationRelativeTo(null);
        otpremnicaForm.setVisible(true);
    }//GEN-LAST:event_btnUpdateOActionPerformed

    private void btnDetailsVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsVActionPerformed
      int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "morate da izaberete neko polje", "greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        List<Vozac> listVozac = Controller.getInstance().getListVozac();
        Vozac vozac = listVozac.get(selectedRow);

        DetailsVozacForm vozacForm = new DetailsVozacForm(this, true, vozac);
        vozacForm.setLocationRelativeTo(null);
        vozacForm.setVisible(true);
    }//GEN-LAST:event_btnDetailsVActionPerformed

    private void btnCreateOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateOActionPerformed

    private void btnDeleteOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteOActionPerformed
       int selectedRow = jTable2.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "morate da izaberete neko polje", "greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        List<Otpremnica> listOtpremnica = Controller.getInstance().getListOtpremnica();
        Otpremnica deleteOtpremnica = listOtpremnica.get(selectedRow);
        boolean result = Controller.getInstance().deleteOtpremnica(deleteOtpremnica);

        if (result) {
            JOptionPane.showMessageDialog(this, "uspesno izbrisana otpremnica");

        } else {
            JOptionPane.showMessageDialog(this, "greska pri brisanju iz baze", "greska", JOptionPane.ERROR_MESSAGE);
        }
        fillTableOtpremnica();
    }//GEN-LAST:event_btnDeleteOActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateO;
    private javax.swing.JButton btnCreateV;
    private javax.swing.JButton btnDeleteO;
    private javax.swing.JButton btnDeleteV;
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnDetailsV;
    private javax.swing.JButton btnUpdateO;
    private javax.swing.JButton btnUpdateV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    private void fillTableVozac() {
        List<Vozac> listVozac = Controller.getInstance().getListVozac();
        TableModelVozac tmv = new TableModelVozac(listVozac);
        jTable1.setModel(tmv);
    }

    private void fillTableOtpremnica() {
        List<Otpremnica> listOtpremnica = Controller.getInstance().getListOtpremnica();
        TableModelOtpremnica tmo = new TableModelOtpremnica(listOtpremnica);
        jTable2.setModel(tmo);
    }
}
