/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import controller.Controller;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import util.TableModelDetailsVozac;
import util.Vozac;
import util.VrstaVozaca;
import util.VzVV;

/**
 *
 * @author Marko
 */
public class MyVrstaVozacaForm extends javax.swing.JDialog {

    private Vozac vozac;

    /**
     * Creates new form UpdateVrstaVozacaForm
     */
    public MyVrstaVozacaForm(java.awt.Frame parent, boolean modal, Vozac vozac) {
        super(parent, modal);
        this.vozac = vozac;
        initComponents();
        fillCombo();
        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        comboVehicles = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        txtDateLicence = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtStartDateLicence = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Moja vrsta vozača");

        btnAdd.setText("Dodaj");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Obriši");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        comboVehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboVehiclesActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Dodaj Vrstu Vozača");

        jLabel4.setText("Vozilo :");

        jLabel5.setText("Kategorija dozvole :");

        lblCategory.setText("kategorija");

        jLabel7.setText("Dozvola traje do :");

        jLabel8.setText("Dozvola traje od :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(176, 176, 176))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addComponent(comboVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(66, 66, 66)
                                .addComponent(lblCategory))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDateLicence, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtStartDateLicence, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(112, 112, 112))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(217, 217, 217))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnDelete)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(comboVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblCategory))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStartDateLicence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDateLicence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(29, 29, 29)
                .addComponent(btnAdd)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String datumPocetakString = txtStartDateLicence.getText();
        String datumKrajString = txtDateLicence.getText();

        String d1[] = datumPocetakString.split("\\.");
        String d[] = datumKrajString.split("\\.");
        if (Controller.isValidDate(datumPocetakString, "dd.MM.yyyy") && Controller.isValidDate(datumKrajString, "dd.MM.yyyy")) {
            String datumPocetak = d1[2] + "-" + d1[1] + "-" + d1[0];
            String datumKraj = d[2] + "-" + d[1] + "-" + d[0];

            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date dateKraj = new Date();
            Date danas = new Date();

            try {
                dateKraj = dateFormat.parse(datumKraj);
            } catch (ParseException e) {
                System.out.println("Greška pri parsiranju datuma: " + e.getMessage());
            }

            VrstaVozaca selected = (VrstaVozaca) comboVehicles.getSelectedItem();
            VzVV selectedDriver = Controller.getInstance().getVzVV(vozac.getIdVozac(), selected);
            System.out.println(selectedDriver);

            if (selectedDriver.getId() == 0) {
                if (dateKraj.before(danas)) {
                    JOptionPane.showMessageDialog(this, "Dozvola koju želite da unesete ne važi", "Greška", JOptionPane.ERROR_MESSAGE);
                } else {
                    boolean result = Controller.getInstance().insertVzVV(vozac.getIdVozac(), selected.getIdVrstaVozaca(), datumPocetak, datumKraj);
                    if (result) {
                        JOptionPane.showMessageDialog(this, "Uspešno sačuvane promene");
                        fillTable();

                    } else {
                        JOptionPane.showMessageDialog(this, "Greška pri čuvanju izmena u bazi", "Greška", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {
                if (selectedDriver.getExpireDateLicence().after(danas)) {
                    JOptionPane.showMessageDialog(this, "Ne možete dodati novu dozvolu jer postoji važeća\nDozvola Vam važi do : " + Controller.getInstance().convertDate(selectedDriver.getExpireDateLicence()) + "", "Greška", JOptionPane.ERROR_MESSAGE);
                } else {
                    boolean result = Controller.getInstance().updateVzVV(selectedDriver.getId(), datumPocetak, datumKraj);
                    if (result) {
                        JOptionPane.showMessageDialog(this, "Uspešno promenjena dozvola");
                        fillTable();

                    } else {
                        JOptionPane.showMessageDialog(this, "Greška pri cuvanju izmena u bazi", "Greška", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Datum koji ste uneli nije validan", "Greška", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Morate da izaberete neko polje", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        List<VzVV> listVzVV = Controller.getInstance().getVzVV(vozac.getIdVozac());
        int delete = listVzVV.get(selectedRow).getId();
        boolean result = Controller.getInstance().deleteVzVV(delete);

        if (result) {
            JOptionPane.showMessageDialog(this, "Uspešno izbrisana vrsta vozača");

        } else {
            JOptionPane.showMessageDialog(this, "Greška pri brisanju iz baze", "Greška", JOptionPane.ERROR_MESSAGE);
        }
        fillTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void comboVehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboVehiclesActionPerformed
        VrstaVozaca selected = (VrstaVozaca) comboVehicles.getSelectedItem();
        lblCategory.setText(selected.getDriverLicence());
    }//GEN-LAST:event_comboVehiclesActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox<VrstaVozaca> comboVehicles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JTextField txtDateLicence;
    private javax.swing.JTextField txtStartDateLicence;
    // End of variables declaration//GEN-END:variables

    private void fillTable() {
        TableModelDetailsVozac detailsVozac = new TableModelDetailsVozac(Controller.getInstance().getVzVV(vozac.getIdVozac()));
        jTable1.setModel(detailsVozac);
    }

    private void fillCombo() {
        List<VrstaVozaca> list = Controller.getInstance().getListVrstaVozaca();
        for (VrstaVozaca vrstaVozaca : list) {
            comboVehicles.addItem(vrstaVozaca);
        }
    }
}
